# Setup
title:               Padmanabh Galgali
tagline:             'A Tech Blog'
description:         'A commonplace for all the tech that I am working on'
url:                 http://padmanabhgalgali.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Padmanabh
  url:               https://twitter.com/padmanabhg1

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
